apps/user/urls.py
# django
from django.urls import path, include
# third
# own
from apps.user.views import Logout

urlpatterns = [
    path('administrator/', include(('apps.user.urls_administrator', 'administrator'))),
    path('supplier/', include(('apps.user.urls_supplier', 'supplier'))),
    path('technical/', include(('apps.user.urls_technical', 'technical'))),
    # path('client/', include(('apps.user.urls_client', 'client'))),
    path('logout/', Logout.as_view(), name='logout'),
]

dj_ryvatec/urls.py
# django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# third
# own
from apps.user.views import Home, Login, Proveedores, Tecnicos, QuienesSomos, AdicionarUsuario

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home'),
    path('user/', include(('apps.user.urls', 'user'))),
    path('proveedores/', Proveedores.as_view(), name='proveedores'),
    path('tecnicos/', Tecnicos.as_view(), name='tecnicos'),
    path('quienes-somos/', QuienesSomos.as_view(), name='quienes_somos'),
    path('adicionar-usuarios/', AdicionarUsuario.as_view(), name='adicionar_usuarios'),
    path('login/', Login.as_view(), name='login'),
]

# Media Files.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/user/models.py
# django
from django.db import models
from django.contrib.auth.models import User
# third
# own

# Create your models here.

ROL_CHOICES = (
    ('AMD', u'Administrador'),
    # ('CLI', u'Cliente'),
    ('PRO', u'Proveedor'),
    ('TEC', u'Tecnico')
)

class Usuario(models.Model):
    '''
    Esta clase se encarga de definir los actributos de la tabla Usuario de la base de datos ryvatec.
    '''
    id_user = models.CharField(primary_key=True, max_length=10)
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    telefono = models.CharField(max_length=15)
    direccion = models.CharField(max_length=60)
    correo = models.EmailField(max_length=150, blank=True, null=True)
    pagina = models.CharField(max_length=150)
    imagen = models.ImageField(upload_to='usuarios/', default='usuarios/ironman.jpg')
    especialidad = models.CharField(max_length=100)
    usuid = models.OneToOneField(User, on_delete=models.CASCADE)
    rol = models.CharField(max_length=20, choices=ROL_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):  # __unicode__
        return self.nombre

    class Meta:
        verbose_name_plural = "Usuarios"
        verbose_name = "Usuario"

class Categoria(models.Model):
    '''Esta clase se encarga de definir los actributos de la tabla Categoria de la base de datos ryvatec.'''
    id_categoria = models.CharField(primary_key=10, max_length=10)
    nombre = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):  # __unicode__
        return self.nombre

    class Meta:
        verbose_name_plural = "Categorias"
        verbose_name = "Categoria"

class Dispositivo(models.Model):
    '''Esta clase se encarga de definir los actributos de la tabla Dispositivo de la base de datos ryvatec.'''
    id_dispositivo = models.CharField(primary_key=True, max_length=10)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30)
    precio = models.IntegerField()
    imagen = models.ImageField(upload_to='dispositivos/')
    descripcion = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):  # __unicode__
        return self.nombre

    class Meta:
        verbose_name_plural = "Dispositivos"
        verbose_name = "Dispositivo"

apps/user/views.py
# django
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
# third
# own
from apps.user.models import Usuario, Dispositivo
from apps.user.forms import AdicionarUsuarioForm, UsuarioForm

# Create your views here.

class Login(View):
    template_name = 'login.html'
    '''Esta clase se encarga del logeo del usuario, de verificar que el usuario y la contraseña sean correctas.'''
    def get(self, request):
        '''
        Esta funcion se encarga de mostrar la plantilla del login.
        :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
        :return: Nos retorna la plantilla login.
        '''
        return render(request, self.template_name)

    def post(self, request):
        '''
        Esta funcion se encarga de verificar que el usuario y la contraseña sean correctas.
        :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
        :return: Nos retorna la plantilla correspondiente al usuario y si se presenta un error
        o inconveniente nos retorna la plantilla login.
        '''
        username = request.POST.get("signin_username")
        password = request.POST.get("signin_password")
        usuario = auth.authenticate(username=username, password=password)

        if usuario != None and usuario.is_active:
            auth.login(request, usuario)
            cliente = Usuario.objects.filter(usuid=usuario.pk)

            # if cliente[0].rol == "CLI":
            #     return HttpResponseRedirect(reverse('cliente:perfil_cliente'))

            if cliente[0].rol == "AMD":
                return HttpResponseRedirect(reverse('user:administrator:home'))

            elif cliente[0].rol == "PRO":
                return HttpResponseRedirect(reverse('user:supplier:home'))

            elif cliente[0].rol == "TEC":
                return HttpResponseRedirect(reverse('user:technical:home'))

            else:
                messages.add_message(request, messages.ERROR, "Rol de usuario inexistente")

        else:
            if usuario == None:
                messages.add_message(request, messages.ERROR, "El Usuario no se encuentra registrado")

            else:
                messages.add_message(request, messages.ERROR, "El Usuario esta inactivo")

        return render(request, self.template_name)


class Logout(View):
    '''Esta clase se encarga de mostrar el login.'''
    def get(self, request):
        '''
        Esta clase se encarga de mostrar la plantilla login.
        :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
        :return: Nos retorna la plantilla login.
        '''
        auth.logout(request)
        return HttpResponseRedirect(reverse('login'))

class Home(View):
    '''Esta clase se encarga de mostrar la plantilla de inicio.'''
    template_name = 'home.html'
    def get(self, request):
        '''
                    Esta funcion se encarga de mostrar todos los dispositivos registrados en el sistema de informacion.
                    :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
                    :return: Nos retorna la plantilla de inicio y todos los dispositivos registrados en el sistema.
                    '''
        lista_dispositivos = Dispositivo.objects.all()
        return render(request, self.template_name, {'list_dispositivos': lista_dispositivos})

class Proveedores(View):
    '''Esta clase se encarga en mostrar la plantilla de proveedores.'''
    template_name = 'proveedores.html'
    def get(self, request):
        '''
                Esta funcion se encarga de mostrar todos los proveedores registrados en el sistema.
                :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
                :return: Nos retorna la plantilla de los proveedores y a todos los proveedores registrados en el sistema.
                '''
        lista_proveedores = Usuario.objects.filter(rol='PRO')
        return render(request, self.template_name, {'list_proveedores': lista_proveedores})

class Tecnicos(View):
    '''Esta clase se encarga de mostrar la plantilla de tecnicos.'''
    template_name = 'tecnicos.html'
    def get(self, request):
        '''
                Esta funcion se encarga de mostrar todos los tecnicos registrados en el sistema.
                :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
                :return: Nos retorna la plantilla de los tecnicos y a todos los tecnicos registrados en el sistema.
                '''
        lista_tecnicos = Usuario.objects.filter(rol='TEC')
        return render(request, self.template_name, {'list_tecnicos': lista_tecnicos})

class QuienesSomos(View):
    '''Esta clase se encarga de mostrarnos la plantilla de quienes somos.'''
    template_name = 'quienes_somos.html'
    def get(self, request):
        '''
                Esta funcion se encarga de mostrar la mision y vision del proyecto ryvatec.
                :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
                :return: Nos retorna la plantilla de quienes somos.
                '''
        return render(request, self.template_name)

class AdicionarUsuario(View):
    '''Esta clase se encarga de agregar los usuarios.'''
    form_class = AdicionarUsuarioForm
    template_name = 'adicionar_usuarios.html'

    def get(self, request):
        '''
        Esta funcion se encarga de mostrarnos la plantilla de adicionar usuario y su respectivo formulario.
        :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
        :return: Nos retorna la plantilla adicionar usuario y su respectivo formulario.
        '''
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        '''
        Esta funcion se encarga de verificar que el usuario se agrego correctamente o de lo contrario si se precento
        algun inconveniente o error.
        :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
        :return: Nos retorna a la plantilla adicionar usuario.
        '''
        username = request.POST.get('username', None)
        email = request.POST.get('email', None)
        correo = request.POST.get('correo', None)
        password = request.POST.get('password', None)
        confirm_password = request.POST.get('confirm_password', None)
        cedula = request.POST.get('id_user', None)
        nombres = request.POST.get('nombre', None)
        apellidos = request.POST.get('apellido', None)
        telefono = request.POST.get('telefono', None)
        pagina = request.POST.get('pagina', None)
        #imagen = request.FILES('imagen', None)
        direccion = request.POST.get('direccion', None)
        rol = request.POST.get('rol', None)

        if password == confirm_password:
            if username and email and password and confirm_password:
                user, created = User.objects.get_or_create(username=username,
                                                            email=email,
                                                            first_name=nombres,
                                                            last_name=apellidos)

                if created:
                    user.set_password(password)
                    user.save()
                    cliente = Usuario(id_user=cedula,
                                        nombre=nombres,
                                        apellido=apellidos,
                                        telefono=telefono,
                                        direccion=direccion,
                                        correo=correo,
                                        pagina=pagina,
                                        #imagen=imagen,
                                        rol=rol,
                                        usuid=user)
                    cliente.save()
                    messages.add_message(request, messages.INFO, "El usuario se agrego satisfactoriamente")

                else:
                    messages.add_message(request, messages.ERROR, "El usuario ya existe en el sistema")

            else:
                messages.add_message(request, messages.ERROR, "Faltan campos por llenar en el formulario")

        else:
            messages.add_message(request, messages.ERROR, "Verifique las contraseña")

        return render(request, self.template_name)

apps/user/templates/client/alerts.html
{%  load static %}
<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/sweetalert.css' %}">
<script src="{% static 'javascripts/jquery.js' %}"></script>
<script src="{% static 'javascripts/sweetalert.min.js' %}"></script>

<div id="alerts">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <script>
                    $(document).ready(function ()
                    {
                        swal(
                        {
                            type: "error",
                            title: "ERROR",
                            text: "{{ message }}",
                            showConfirmButton: true
                        });
                    })
                </script>

            {% else %}
                <script>
                    $(document).ready(function ()
                    {
                        swal(
                        {
                            type: "success",
                            title: "INFORMACIÓN",
                            text: "{{ message }}",
                            showConfirmButton: true
                        });
                    })
                </script>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

apps/user/templates/client/base_cliente.html
{% load static %}

<!DOCTYPE html>
    <!--[if IE 8]>         <html class="ie8"> <![endif]-->
    <!--[if IE 9]>         <html class="ie9 gt-ie8"> <![endif]-->
    <!--[if gt IE 9]><!--> <html class="gt-ie8 gt-ie9 not-ie"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Banco</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
        <!-- Open Sans font from Google CDN -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">
        <!-- Pixel Admin's stylesheets -->
        <link href="{% static 'stylesheets/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/pixel-admin.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/widgets.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/pages.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/rtl.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/themes.min.css' %}" rel="stylesheet" type="text/css">

        {% block styles %}
        {% endblock %}

        <!--[if lt IE 9]>
            <script src="{% static 'javascripts/ie.min.js' %}"></script>
        <![endif]-->
    </head>

    <body class="theme-adminflare main-menu-animated">
        <div id="main-wrapper">
            <div id="main-navbar" class="navbar navbar-inverse" role="navigation">
                <!-- Main menu toggle -->
                <button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">HIDE MENU</span></button>

                <div class="navbar-inner">
                    <!-- Main navbar header -->
                    <div class="navbar-header">

                        <!-- Logo -->
                        <a href="" class="navbar-brand">
                            <div><img alt="Pixel Admin" src="{% static 'images/pixel-admin/main-navbar-logo.png' %}"></div>
                            Cliente
                        </a>

                        <!-- Main navbar toggle -->
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

                    </div> <!-- / .navbar-header -->

                    <div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
                        <div>
                            <div class="right clearfix">
                                <ul class="nav navbar-nav pull-right right-navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
                                            <span class="btn-label icon fa fa-user"></span>
                                            <span>{{ user.first_name }}&nbsp;{{ user.last_name }}</span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="{% url 'cliente:perfil_cliente' %}">
                                                    <i class="dropdown-icon fa fa-user"></i>&nbsp;&nbsp;Perfil
                                                </a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="{% url 'user:logout' %}">
                                                    <i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Cerrar Sesión
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul> <!-- / .navbar-nav -->
                            </div> <!-- / .right -->
                        </div>
                    </div> <!-- / #main-navbar-collapse -->
                </div> <!-- / .navbar-inner -->
            </div> <!-- / #main-navbar -->
        <!-- /2. $END_MAIN_NAVIGATION -->
            <div id="main-menu" role="navigation">
                <div id="main-menu-inner">
                    <div class="menu-content top" id="menu-content-demo">
                        <div>
                            <div class="text-bg">
                                <span class="text-slim">Bienvenido,</span><br>
                                <span class="text-semibold">{{ user.first_name }}</span>
                            </div>
                            <img src="{% static 'images/usuario.jpg'%}" id="img_usuario" alt="Foto Usuario" style="background: white;">
                        </div>
                    </div>
                    <div>
                        <ul class="navigation">
                            <li>
                                <a href="{% url 'cliente:perfil_cliente' %}">
                                    <i class="menu-icon fa fa-user"></i>
                                    <span class="mm-text">Perfil</span>
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    <i class="menu-icon fa fa-eye"></i>
                                    <span class="mm-text">Nose</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'user:logout' %}">
                                    <i class="menu-icon fa fa-power-off"></i>
                                    <span class="mm-text">Cerrar Sesion</span>
                                </a>
                            </li>
                        </ul> <!-- / .navigation -->
                    </div>
                </div> <!-- / #main-menu-inner -->
            </div> <!-- / #main-menu -->
        <!-- /4. $MAIN_MENU -->
            <div id="content-wrapper">

                {% block content %}
                    {% include 'alerts.html' %}
                {% endblock %}

            </div> <!-- / #content-wrapper -->
            <div id="main-menu-bg"></div>
        </div> <!-- / #main-wrapper -->
        <!-- Get jQuery from Google CDN -->
        <!--[if !IE]> -->
            <script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js">'+"<"+"/script>"); </script>
        <!-- <![endif]-->
        <!--[if lte IE 9]>
            <script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js">'+"<"+"/script>"); </script>
        <![endif]-->
        <!-- Pixel Admin's javascripts -->
        <script src="{% static 'javascripts/bootstrap.min.js' %}"></script>
        <script src="{% static 'javascripts/pixel-admin.min.js' %}"></script>
        <script>var init = [];</script>
        <script type="text/javascript">
            init.push(function () {});
            window.PixelAdmin.start(init);
        </script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

apps/user/templates/client/perfil_cliente.html
{% extends 'cliente/base_cliente.html' %}
{% load static %}
{% block styles %}
{% endblock %}

{% block content %}
    {% include 'cliente/alerts.html' %}
    <div class="page-header">
        <div class="row">
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>
                &nbsp;&nbsp;Perfil Cliente
            </h1>
        </div>
    </div>
    <div class="profile-full-name">
        <span class="text-semibold">
            <i class="fa fa-edit page-header-icon"></i>
            Datos Cliente
        </span>
    </div>

    <div class="right-col">
            <hr class="profile-content-hr no-grid-gutter-h">
            <div class="profile-content">
                <div class="panel">
                    <br><br>
                    <form method="post" id="form_usuario" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.errors }}
                                <label for="jq-validation-url" class="col-sm-3 control-label">
                                    <strong>{{ field.label }}</strong>
                                </label>
                                <div class="col-sm-9">
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                        <br>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <a href="{% url 'cliente:perfil_cliente' %}">
                                    <button type="submit" class="btn btn-primary">
                                        <span class="btn-label icon fa fa-pencil"></span>
                                        Modificar
                                    </button>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        init.push(function ()
        {
            $('body').addClass("page-profile");
            $('#item_usuario').addClass("active");
        });

        window.PixelAdmin.start(init);
    </script>

    {% block scripts_crud %}
        <script>
            $('#id_rol').attr('style', 'pointer-events: none;');
            $('#id_usuid').attr('style', 'pointer-events: none;');
            $('#id_cedula').prop('readonly',true);
        </script>
    {% endblock %}
{% endblock %}