apps/user/urls.py
# django
from django.urls import path, include
# third
# own
from apps.user.views import Logout

urlpatterns = [
    path('administrator/', include(('apps.user.urls_administrator', 'administrator'))),
    path('supplier/', include(('apps.user.urls_supplier', 'supplier'))),
    path('technical/', include(('apps.user.urls_technical', 'technical'))),
    # path('client/', include(('apps.user.urls_client', 'client'))),
    path('logout/', Logout.as_view(), name='logout'),
]

dj_ryvatec/urls.py
# django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# third
# own
from apps.user.views import Home, Login, Proveedores, Tecnicos, QuienesSomos, AdicionarUsuario

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home'),
    path('user/', include(('apps.user.urls', 'user'))),
    path('proveedores/', Proveedores.as_view(), name='proveedores'),
    path('tecnicos/', Tecnicos.as_view(), name='tecnicos'),
    path('quienes-somos/', QuienesSomos.as_view(), name='quienes_somos'),
    path('adicionar-usuarios/', AdicionarUsuario.as_view(), name='adicionar_usuarios'),
    path('login/', Login.as_view(), name='login'),
]

# Media Files.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/user/models.py
# django
from django.db import models
from django.contrib.auth.models import User
# third
# own

# Create your models here.

ROL_CHOICES = (
    ('AMD', u'Administrador'),
    # ('CLI', u'Cliente'),
    ('PRO', u'Proveedor'),
    ('TEC', u'Tecnico')
)

class Usuario(models.Model):
    '''
    Esta clase se encarga de definir los actributos de la tabla Usuario de la base de datos ryvatec.
    '''
    id_user = models.CharField(primary_key=True, max_length=10)
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    telefono = models.CharField(max_length=15)
    direccion = models.CharField(max_length=60)
    correo = models.EmailField(max_length=150, blank=True, null=True)
    pagina = models.CharField(max_length=150)
    imagen = models.ImageField(upload_to='usuarios/', default='usuarios/ironman.jpg')
    especialidad = models.CharField(max_length=100)
    usuid = models.OneToOneField(User, on_delete=models.CASCADE)
    rol = models.CharField(max_length=20, choices=ROL_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):  # __unicode__
        return self.nombre

    class Meta:
        verbose_name_plural = "Usuarios"
        verbose_name = "Usuario"

class Categoria(models.Model):
    '''Esta clase se encarga de definir los actributos de la tabla Categoria de la base de datos ryvatec.'''
    id_categoria = models.CharField(primary_key=10, max_length=10)
    nombre = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):  # __unicode__
        return self.nombre

    class Meta:
        verbose_name_plural = "Categorias"
        verbose_name = "Categoria"

class Dispositivo(models.Model):
    '''Esta clase se encarga de definir los actributos de la tabla Dispositivo de la base de datos ryvatec.'''
    id_dispositivo = models.CharField(primary_key=True, max_length=10)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30)
    precio = models.IntegerField()
    imagen = models.ImageField(upload_to='dispositivos/')
    descripcion = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):  # __unicode__
        return self.nombre

    class Meta:
        verbose_name_plural = "Dispositivos"
        verbose_name = "Dispositivo"

apps/user/views.py
# django
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
# third
# own
from apps.user.models import Usuario, Dispositivo
from apps.user.forms import AdicionarUsuarioForm, UsuarioForm

# Create your views here.

class Login(View):
    template_name = 'login.html'
    '''Esta clase se encarga del logeo del usuario, de verificar que el usuario y la contraseña sean correctas.'''
    def get(self, request):
        '''
        Esta funcion se encarga de mostrar la plantilla del login.
        :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
        :return: Nos retorna la plantilla login.
        '''
        return render(request, self.template_name)

    def post(self, request):
        '''
        Esta funcion se encarga de verificar que el usuario y la contraseña sean correctas.
        :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
        :return: Nos retorna la plantilla correspondiente al usuario y si se presenta un error
        o inconveniente nos retorna la plantilla login.
        '''
        username = request.POST.get("signin_username")
        password = request.POST.get("signin_password")
        usuario = auth.authenticate(username=username, password=password)

        if usuario != None and usuario.is_active:
            auth.login(request, usuario)
            cliente = Usuario.objects.filter(usuid=usuario.pk)

            # if cliente[0].rol == "CLI":
            #     return HttpResponseRedirect(reverse('cliente:perfil_cliente'))

            if cliente[0].rol == "AMD":
                return HttpResponseRedirect(reverse('user:administrator:home'))

            elif cliente[0].rol == "PRO":
                return HttpResponseRedirect(reverse('user:supplier:home'))

            elif cliente[0].rol == "TEC":
                return HttpResponseRedirect(reverse('user:technical:home'))

            else:
                messages.add_message(request, messages.ERROR, "Rol de usuario inexistente")

        else:
            if usuario == None:
                messages.add_message(request, messages.ERROR, "El Usuario no se encuentra registrado")

            else:
                messages.add_message(request, messages.ERROR, "El Usuario esta inactivo")

        return render(request, self.template_name)


class Logout(View):
    '''Esta clase se encarga de mostrar el login.'''
    def get(self, request):
        '''
        Esta clase se encarga de mostrar la plantilla login.
        :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
        :return: Nos retorna la plantilla login.
        '''
        auth.logout(request)
        return HttpResponseRedirect(reverse('login'))

class Home(View):
    '''Esta clase se encarga de mostrar la plantilla de inicio.'''
    template_name = 'home.html'
    def get(self, request):
        '''
                    Esta funcion se encarga de mostrar todos los dispositivos registrados en el sistema de informacion.
                    :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
                    :return: Nos retorna la plantilla de inicio y todos los dispositivos registrados en el sistema.
                    '''
        lista_dispositivos = Dispositivo.objects.all()
        return render(request, self.template_name, {'list_dispositivos': lista_dispositivos})

class Proveedores(View):
    '''Esta clase se encarga en mostrar la plantilla de proveedores.'''
    template_name = 'proveedores.html'
    def get(self, request):
        '''
                Esta funcion se encarga de mostrar todos los proveedores registrados en el sistema.
                :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
                :return: Nos retorna la plantilla de los proveedores y a todos los proveedores registrados en el sistema.
                '''
        lista_proveedores = Usuario.objects.filter(rol='PRO')
        return render(request, self.template_name, {'list_proveedores': lista_proveedores})

class Tecnicos(View):
    '''Esta clase se encarga de mostrar la plantilla de tecnicos.'''
    template_name = 'tecnicos.html'
    def get(self, request):
        '''
                Esta funcion se encarga de mostrar todos los tecnicos registrados en el sistema.
                :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
                :return: Nos retorna la plantilla de los tecnicos y a todos los tecnicos registrados en el sistema.
                '''
        lista_tecnicos = Usuario.objects.filter(rol='TEC')
        return render(request, self.template_name, {'list_tecnicos': lista_tecnicos})

class QuienesSomos(View):
    '''Esta clase se encarga de mostrarnos la plantilla de quienes somos.'''
    template_name = 'quienes_somos.html'
    def get(self, request):
        '''
                Esta funcion se encarga de mostrar la mision y vision del proyecto ryvatec.
                :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
                :return: Nos retorna la plantilla de quienes somos.
                '''
        return render(request, self.template_name)

class AdicionarUsuario(View):
    '''Esta clase se encarga de agregar los usuarios.'''
    form_class = AdicionarUsuarioForm
    template_name = 'adicionar_usuarios.html'

    def get(self, request):
        '''
        Esta funcion se encarga de mostrarnos la plantilla de adicionar usuario y su respectivo formulario.
        :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
        :return: Nos retorna la plantilla adicionar usuario y su respectivo formulario.
        '''
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        '''
        Esta funcion se encarga de verificar que el usuario se agrego correctamente o de lo contrario si se precento
        algun inconveniente o error.
        :param request: Objeto que contiene todos los parametros enviados por la peticion del cliente al servidor.
        :return: Nos retorna a la plantilla adicionar usuario.
        '''
        username = request.POST.get('username', None)
        email = request.POST.get('email', None)
        correo = request.POST.get('correo', None)
        password = request.POST.get('password', None)
        confirm_password = request.POST.get('confirm_password', None)
        cedula = request.POST.get('id_user', None)
        nombres = request.POST.get('nombre', None)
        apellidos = request.POST.get('apellido', None)
        telefono = request.POST.get('telefono', None)
        pagina = request.POST.get('pagina', None)
        #imagen = request.FILES('imagen', None)
        direccion = request.POST.get('direccion', None)
        rol = request.POST.get('rol', None)

        if password == confirm_password:
            if username and email and password and confirm_password:
                user, created = User.objects.get_or_create(username=username,
                                                            email=email,
                                                            first_name=nombres,
                                                            last_name=apellidos)

                if created:
                    user.set_password(password)
                    user.save()
                    cliente = Usuario(id_user=cedula,
                                        nombre=nombres,
                                        apellido=apellidos,
                                        telefono=telefono,
                                        direccion=direccion,
                                        correo=correo,
                                        pagina=pagina,
                                        #imagen=imagen,
                                        rol=rol,
                                        usuid=user)
                    cliente.save()
                    messages.add_message(request, messages.INFO, "El usuario se agrego satisfactoriamente")

                else:
                    messages.add_message(request, messages.ERROR, "El usuario ya existe en el sistema")

            else:
                messages.add_message(request, messages.ERROR, "Faltan campos por llenar en el formulario")

        else:
            messages.add_message(request, messages.ERROR, "Verifique las contraseña")

        return render(request, self.template_name)

apps/user/templates/administrator/alerts.html
{%  load static %}
<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/sweetalert.css' %}">
<script src="{% static 'javascripts/jquery.js' %}"></script>
<script src="{% static 'javascripts/sweetalert.min.js' %}"></script>

<div id="alerts">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <script>
                    $(document).ready(function ()
                    {
                        swal(
                        {
                            type: "error",
                            title: "ERROR",
                            text: "{{ message }}",
                            showConfirmButton: true
                        });
                    })
                </script>

            {% else %}
                <script>
                    $(document).ready(function ()
                    {
                        swal(
                        {
                            type: "success",
                            title: "INFORMACIÓN",
                            text: "{{ message }}",
                            showConfirmButton: true
                        });
                    })
                </script>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

apps/user/templates/administrator/base_crud_usuario.html
{% extends 'administrator/base_administrador.html' %}
{% load static %}
{% block styles %}
{% endblock %}

{% block content %}
    <div class="page-header">
        <div class="row">
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>
                &nbsp;&nbsp;Administrar Usuarios
            </h1>
        </div>
    </div>
    <div class="profile-full-name">
        <span class="text-semibold">
            {% block titulo_formulario_usuario %}
            {% endblock %}
        </span>
    </div>
    <div class="profile-row">
        <div class="left-col">
            <div class="profile-block">
                <div class="panel profile-photo">
                    <img src="">
                </div>
            </div>
        </div>
        <div class="right-col">
            <hr class="profile-content-hr no-grid-gutter-h">
            <div class="profile-content">
                <div class="panel">
                    <br><br>
                    <form method="post" id="form_usuario" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {% include 'administrator/form_usuario.html' %}
                        <br>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                {% block boton_accion_usuario %}
                                {% endblock %}
                                <a href="{% url 'user:administrator:listar_usuarios' %}">
                                    <button type="button" class="btn btn-danger">Salir</button>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        init.push(function ()
        {
            $('body').addClass("page-profile");
            $('#item_usuario').addClass("active");
        });

        window.PixelAdmin.start(init);
    </script>

    {% block scripts_crud %}
    {% endblock %}
{% endblock %}

apps/user/templates/administrator/borrar_categoria.html
{% extends 'administrator/base_crud_categoria.html' %}

{% block titulo_formulario_categoria %}
    <i class="fa fa-eraser page-header-icon"></i>&nbsp;Borrar Categoria
{% endblock %}

{% block boton_accion_categoria %}
    <button type="submit" class="btn btn-primary">
        <span class="btn-label icon fa fa-eraser"></span>
        Borrar
    </button>
{% endblock %}

{% block scripts_crud %}
    <script>
        $('#form_usuario').find("input[type='text'], input[type='number'], input[type='file'], select, textarea").each(function (index, element)
        {
            $(element).prop('readonly', true);
            $(element).prop('disabled', true);
        });

        $('#form_usuario').find("select").each(function (index, element)
        {
            $(element).attr('style', 'pointer-events: none;');
        });
    </script>
{% endblock %}

apps/user/templates/administrator/borrar_usuario.html
{% extends 'administrator/base_crud_usuario.html' %}

{% block titulo_formulario_usuario %}
    <i class="fa fa-eraser page-header-icon"></i>&nbsp;Borrar Usuario
{% endblock %}

{% block boton_accion_usuario %}
    <button type="submit" class="btn btn-primary">
        <span class="btn-label icon fa fa-eraser"></span>
        Borrar
    </button>
{% endblock %}

{% block scripts_crud %}
    <script>
        $('#form_usuario').find("input[type='text'], input[type='number'], input[type='file'], select, textarea").each(function (index, element)
        {
            $(element).prop('readonly', true);
            $(element).prop('disabled', true);
        });

        $('#form_usuario').find("select").each(function (index, element)
        {
            $(element).attr('style', 'pointer-events: none;');
        });
        $('#id_correo').prop('readonly', true);
    </script>
{% endblock %}

apps/user/templates/administrator/form_usuario.html
{% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        <label for="jq-validation-url" class="col-sm-3 control-label">
            <strong>{{ field.label }}</strong>
        </label>
        <div class="col-sm-9">
            {{ field }}
        </div>
    </div>
{% endfor %}

apps/user/templates/administrator/home.html
{% extends 'administrator/base_administrador.html' %}
{% block content %}
    {% include 'alerts.html' %}
    <header style="width: 1100px; height: 200px; margin-left: 20px; margin-top: 20px;">
        <div style="float: left; width: 734px; height: 180px; margin-left: 10px; margin-top: 10px;">
            <h1 style="font-family: Helvetica; font-size: 24px; text-align: center; margin-top: 70px;">
                Reparacion Y Venta de Aparatos Tecnologicos(RYVATEC.com)
            </h1>
        </div>
        <div style="float: left; width: 331px; height: 180px; margin-left: 10px; margin-top: 10px; background-image: url(../../../static/demo/ORIGINAL.png);">
        </div>
    </header>
    <section style="width: 1100px; height: 636px; margin-left: 20px; overflow: auto;">
        {% for dispositivo in list_dispositivos %}
            <div class="dispositivo" style="float: left; width: 207px; height: 300px; margin-left: 10px; margin-top: 10px; overflow: auto;">
                <div style="position: center; width: 205.1px; height: 150px;">
                    <img src="{{ dispositivo.imagen.url }}" style="width: 205px; height: 150px;">
                </div>
                Nombre: {{ dispositivo.nombre }}<br />
                Precio: {{ dispositivo.precio }}<br />
                Descripcion: {{ dispositivo.descripcion }}<br />
                Proveedor: {{ dispositivo.usuario }}<br />
                Telefono: {{ dispositivo.usuario.telefono }}<br />
                Direccion: {{ dispositivo.usuario.direccion }}<br />
                Pagina Web: <a href="http://{{ dispositivo.usuario.pagina }}">{{ dispositivo.usuario.pagina }}</a>
            </div>
        {% endfor %}
    </section>
    <footer style="width: 1100px; height: 132px; margin-left: 20px;">
        <div style="float: left; width:864px; height: 110px; margin-left: 10px; margin-top: 10px;" >
            <h5 style="float: left; margin-left: 10px; margin-top: 18px;">
                Trabaja con nosotros
            </h5>
            <h5 style="float: left; margin-left: 60px; margin-top: 18px;">
                Terminos y Condiciones
            </h5>
            <h5 style="float: left; margin-left: 60px; margin-top: 18px; ">
                Contactos<br />
                Telefono: <br />
                Celular: <br />
            </h5>
            <h5 style="float: left; margin-left: 100px; margin-top: 18px; ">
                Redes Sociales<br />
                Facebook: <br />
                Instagram: <br />
            </h5>
            <h3 style="margin-left: 10px; margin-top: 78px; font-family: Helvetica; font-size: 10px;">
                Copyright 2018-2019 RYVATEC.com
            </h3>
        </div>
        <div style="float: left; width: 200px; height: 110px; margin-top: 10px; margin-left: 10px; background-image: url(../../../static/demo/ORIGINAL-FOOTER.png);">
        </div>
    </footer>
{% endblock %}

apps/user/templates/administrator/listar_categoria.html
{% extends 'administrator/base_administrador.html' %}

{% block styles %}
{% endblock %}

{% block content %}
    {% include 'administrator/alerts.html' %}
    <div class="page-header">
        <div class="row">
            <!-- Page header, center on small screens -->
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>&nbsp;&nbsp;Administración de Categorias
            </h1>
            <div class="col-xs-12 col-sm-8">
                <div class="row">
                    <hr class="visible-xs no-grid-gutter-h">
                    <!-- "Create project" button, width=auto on desktops -->
                    <div class="pull-right col-xs-12 col-sm-auto">
                        <a href="{% url 'user:administrator:adicionar_categoria' %}">
                            <button class="btn  btn-labeled btn-primary" >
                               <span class="btn-label icon fa fa-plus"></span>
                                Adicionar Categoria
                            </button>&nbsp;&nbsp;
                        </a>
                    </div>
                    <!-- Margin -->
                    <div class="visible-xs clearfix form-group-margin"></div>
                    <!-- Search field -->
                </div>
            </div>
        </div>
    </div> <!-- / .page-header -->
    <!-- / Javascript -->
    <div class="panel">
        {% csrf_token %}
        <div class="panel-body">
            <div class="table-primary">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="jq-datatables-example">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Id Categoria</th>
                            <th>Nombre</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for categoria in categorias %}
                            <tr class="odd gradeX">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ categoria.id_categoria }}</td>
                                <td>{{ categoria.nombre }}</td>
                                <td>
                                    <div class="btn-group" >
                                        <a href="{% url 'user:administrator:visualizar_categoria' categoria.pk %}" class="btn btn-primary">
                                            <span class="btn-label icon fa fa-eye"></span>
                                            Visualizar
                                        </a>
                                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                            <i class="fa fa-caret-down"></i>
                                        </button>

                                        <ul class="dropdown-menu" style="z-index: 100 !important;">
                                            <li>
                                                <a href="{% url 'user:administrator:modificar_categoria' categoria.pk %}">
                                                    <span class="btn-label icon fa fa-pencil"></span>
                                                    Modificar
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{% url 'user:administrator:borrar_categoria' categoria.pk %}">
                                                    <span class="btn-label icon fa fa-eraser"></span>
                                                    Borrar&nbsp;&nbsp;
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        init.push(function ()
        {
            $('#jq-datatables-example').dataTable();
            $('#jq-datatables-example_wrapper .table-caption').text('Listado de Usuarios');
            $('#jq-datatables-example_wrapper .dataTables_filter input').attr('placeholder', 'Buscar...');
        });
    </script>
{% endblock %}

apps/user/templates/administrator/modificar_categoria.html
{% extends 'administrator/base_crud_categoria.html' %}

{% block titulo_formulario_categoria %}
    <i class="fa fa-edit page-header-icon"></i>&nbsp;Modificar Categoria
{% endblock %}

{% block boton_accion_categoria %}
    <button type="submit" class="btn btn-primary">
        <span class="btn-label icon fa fa-pencil"></span>
        Modificar
    </button>
{% endblock %}

apps/user/templates/administrator/modificar_usuario.html
{% extends 'administrator/base_crud_usuario.html' %}

{% block titulo_formulario_usuario %}
    <i class="fa fa-edit page-header-icon"></i>&nbsp;Modificar Usuario
{% endblock %}

{% block boton_accion_usuario %}
    <button type="submit" class="btn btn-primary">
        <span class="btn-label icon fa fa-pencil"></span>
        Modificar
    </button>
{% endblock %}

apps/user/templates/administrator/proveedores.html
{% extends 'administrator/base_administrador.html' %}

{% block content %}
    {% include 'alerts.html' %}
    <header style="width: 1100px; height: 200px; margin-left: 20px; margin-top: 20px;">
        <div style="float: left; width: 734px; height: 180px; margin-left: 10px; margin-top: 10px;">
            <h1 style="font-family: Helvetica; font-size: 24px; text-align: center; margin-top: 70px;">
                Reparacion Y Venta de Aparatos Tecnologicos(RYVATEC.com)
            </h1>
        </div>
        <div style="float: left; width: 331px; height: 180px; margin-left: 10px; margin-top: 10px; background-image: url(../../../static/demo/ORIGINAL.png);">
        </div>
    </header>
    <section style="width: 1100px; height: 636px; margin-left: 20px; overflow: auto;">
        {% for proveedor in list_proveedores  %}
            <div class="proveedor" style="float: left; margin-top: 10px; width: 207px; height: 300px; margin-left: 10px; overflow: auto;">
                <div style="position: center; width: 205.2px; height: 150px;">
                    <img src="{{ proveedor.imagen.url }}" style="width: 205px; height: 150px;">
                </div>
                Nombre: {{proveedor.nombre}}<br />
                Apellido: {{ proveedor.apellido }}<br />
                Telefono: {{ proveedor.telefono }}<br />
                Direccion: {{ proveedor.direccion }}<br />
                Correo: {{ proveedor.correo }}<br />
                Pagina Web: <a href="http://{{ proveedor.pagina }}">{{ proveedor.pagina }}</a>
            </div>
        {% endfor %}
    </section>
    <footer style="width: 1100px; height: 132px; margin-left: 20px;">
        <div style="float: left; width:864px; height: 110px; margin-left: 10px; margin-top: 10px;" >
            <h5 style="float: left; margin-left: 10px; margin-top: 18px;">
                Trabaja con nosotros
            </h5>
            <h5 style="float: left; margin-left: 60px; margin-top: 18px;">
                Terminos y Condiciones
            </h5>
            <h5 style="float: left; margin-left: 60px; margin-top: 18px; ">
                Contactos<br />
                Telefono: <br />
                Celular: <br />
            </h5>
            <h5 style="float: left; margin-left: 100px; margin-top: 18px; ">
                Redes Sociales<br />
                Facebook: <br />
                Instagram: <br />
            </h5>
            <h3 style="margin-left: 10px; margin-top: 78px; font-family: Helvetica; font-size: 10px;">
                Copyright 2018-2019 RYVATEC.com
            </h3>
        </div>
        <div style="float: left; width: 200px; height: 110px; margin-top: 10px; margin-left: 10px; background-image: url(../../../static/demo/ORIGINAL-FOOTER.png);">
        </div>
    </footer>
{% endblock %}

apps/user/templates/administrator/visualizar_categoria.html
{% extends 'administrator/base_crud_categoria.html' %}

{% block titulo_formulario_categoria %}
    <i class="fa fa-eye page-header-icon"></i>&nbsp;Visualizar Categoria
{% endblock %}

{% block boton_accion_categoria %}
{% endblock %}

{% block scripts_crud %}
    <script>
        $('#form_usuario').find("input[type='text'], input[type='number'], input[type='file'], select, textarea").each(function (index, element)
        {
            $(element).prop('readonly', true);
            $(element).prop('disabled', true);
        });

        $('#form_usuario').find("select").each(function (index, element)
        {
            $(element).attr('style', 'pointer-events: none;');
        });
    </script>
{% endblock %}

apps/user/templates/administrator/visualizar_usuario.html
{% extends 'administrator/base_crud_usuario.html' %}

{% block titulo_formulario_usuario %}
    <i class="fa fa-eye page-header-icon"></i>&nbsp;Visualizar Usuario
{% endblock %}

{% block boton_accion_usuario %}
{% endblock %}

{% block scripts_crud %}
    <script>
        $('#form_usuario').find("input[type='text'], input[type='number'], input[type='file'], select, textarea").each(function (index, element)
        {
            $(element).prop('readonly', true);
            $(element).prop('disabled', true);
        });

        $('#form_usuario').find("select").each(function (index, element)
        {
            $(element).attr('style', 'pointer-events: none;');
        });
        $('#id_correo').prop('readonly', true);
    </script>
{% endblock %}